### ISSUE TITLE
Community Meeting July 31, 2024

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/community#48]
Overview
 At 10am Eastern, 7am Pacific, 2pm UTC; find your time

Video call link: [meet.google.com/ved-ivnv-aen](https://meet.google.com/ved-ivnv-aen)
 dial-in: (US) +1 409-444-2447‬
 PIN: ‪873 550 579#‬
 More phone numbers: tel.meet/ved-ivnv-aen?pin=7872592963542&hs=1

Add topics you'd like to discuss below!

**Comment by lcarva** [comment]
We ran out of time last week. This one was not covered.

- rolling forward or backporting hermetic builds ([EC-748](https://issues.redhat.com/browse/EC-748))

**Comment by arewm** [comment]
I would like to discuss the rule [Trusted parameters](https://github.com/enterprise-contract/ec-policies/blob/main/policy/release/trusted_task.rego#L168). I am not convinced that we are getting any additional protection by preventing untrusted digests from being passed as parameters to trusted tasks.

The intention behind creating the trusted tasks was so that we can have clear provenance of the data that is transmitted between tasks. This prevents the data (i.e. PVCs) from being tampered with by some other task. When we are considering parameters to these tasks, however, all values are recorded in the provenance. Most of the parameters that are passed are not used by the build platform (i.e. the scripts in the task steps) and are only used during the build itself (i.e. within the buildah build command). Therefore, providing untrusted/unvalidated values in these parameters is no different the committing the content to the git repository. The artifacts produced would still be evaluated by the policy as they normally would, i.e.:

* Build is produced in a hermetic environment (i.e. an image passed as a BUILD_ARG would not have any additional capabilities than one committed to git).
* All Image Manifests are verified as trusted (i.e. a "random" image manifest added to an image index would cause the image to fail verification as all manifests are checked).

If we want to be able to restrict parameters from being passed to prevent the behavior of the task from changing, I think we should be more concerned about the provenance of _specific_ parameters than the content of those parameters. For example, if we did still enable a modification of the buildah binary, it could only be specified by a result returned from another trusted task (but not from direct user input). This check would then be replaced by one that has a default-deny policy with an allow-list of task.param.name coordinates identifying specific parameters which can be "safely consumed" without having to be concerned about it impacting the build system.
